#include <stdio.h>
#include "ft_printf.h"

int				main()
{
	printf("Test0\nstd:\n");
	printf("yowyowyow");
	printf("\nft:\n");
	ft_printf("yowyowyow");
	printf("\n");
	printf("Test1\nstd:\n");
	printf("un ptit int : %d", 42);
	printf("\nft:\n");
	ft_printf("un ptit int : %d", 42);
	printf("\n");
	printf("Test2\nstd:\n");
	printf("%d pl%hhd%dn de pt%dts %dn%ds : %d, %hhd", 1337, 1, 3, 1, 1, 7, 42, 999999);
	printf("\nft:\n");
	ft_printf("%d pl%hhd%dn de pt%dts %dn%ds : %d, %hhd", 1337, 1, 3, 1, 1, 7, 42, 999999);
	printf("\n");
	printf("Test3\nstd:\n");
	printf("%s", "une chaine de char");
	printf("\nft:\n");
	ft_printf("%s", "une chaine de char");
	printf("\n");
	printf("Test4\nstd:\n");
	printf("%sl%sd%sde %s", "p", "ein ", "e chaines ", "char");
	printf("\nft:\n");
	ft_printf("%sl%sd%sde %s", "p", "ein ", "e chaines ", "char");
	printf("\n");
	printf("Test5\nstd:\n");
	printf("un octal : %o", 0640);
	printf("\nft:\n");
	ft_printf("un octal : %o", 0640);
	printf("\n");
	printf("Test6\nstd:\n");
	printf("%o pl%o%on de pt%ots oct%oux : %#o", 01337, 1, 3, 1, 4, 042);
	printf("\nft:\n");
	ft_printf("%o pl%o%on de pt%ots oct%oux : %#o", 01337, 1, 3, 1, 4, 042);
	printf("\n");
	printf("Test7\nstd:\n");
	printf("un hex : %x", 0x1337a);
	printf("\nft:\n");
	ft_printf("un hex : %x", 0x1337a);
	printf("\n");
	printf("Test7b\nstd:\n");
	printf("un hex avec # : %#x", 0x1337);
	printf("\nft:\n");
	ft_printf("un hex avec # : %#x", 0x1337);
	printf("\n");
	printf("Test7c\nstd:\n");
	printf("un hex en caps: %X", 0xABCD);
	printf("\nft:\n");
	ft_printf("un hex en caps: %X", 0xABCD);
	printf("\n");
	printf("Test8\nstd:\n");
	unsigned int hex = 0x1337;
	printf("un pointeur sur void : %p", &hex);
	printf("\nft:\n");
	ft_printf("un pointeur sur void : %p", &hex);
	printf("\n");
	printf("Test9\nstd:\n");
	printf("%clein d%c%cchar%c", 'p', 'e', ' ', 's');
	printf("\nft:\n");
	ft_printf("%clein d%c%cchar%c", 'p', 'e', ' ', 's');
	printf("\n");
	printf("Test10\nstd:\n");
	printf("des %% : %% %% %%");
	printf("\nft:\n");
	ft_printf("des %% : %% %% %%");
	printf("\n");
	printf("Test11\nstd:\n");
	printf("des %% %s : %%%s%%%s%%%s", "et d'autres trucs", " ", " ", "");
	printf("\nft:\n");
	ft_printf("des %% %s : %%%s%%%s%%%s", "et d'autres trucs", " ", " ", "");
	printf("\n");
	return (0);
}